### ISSUE TITLE
Lots of Crashes

### ISSUE THREAD

**Issue by Tapato97** [davidlukerice/genSynth#3]
Don't know if this is just my computer, but I seem to get a lot of crashes when using this. It seems like it happens most when multiple instruments are going at once, or when they have high sound intensity.

**Comment by davidlukerice** [comment]
@Tapato97 There's been some issues on Chrome that I thought had been fixed but may be cropping back up. What browser, operating system, and system specs (cpu, memory) are you using? The app can be quite a resource hog.

**Comment by davidlukerice** [comment]
@Tapato97 Is the latest version any more stable?

**Comment by davidlukerice** [comment]
After updating to chrome 40 I haven't seen the issue come up. I'm assuming it was caused by one of the memory corruption or webaudio bugs that was fixed (http://googlechromereleases.blogspot.com/2015/01/stable-update.html). Let me know if it happens again
